### ISSUE TITLE
Unable to access window.location from Microsoft Edge

### ISSUE THREAD

**Issue by chirag64** [forcedotcom/aura#115]
We're trying to access the `window.location` from our Helper function (called from Controller function) to get access to the URL and the query parameters, which works fine on all browsers except on Microsoft Edge. 
When we try to access it from Microsoft Edge, we get an error saying `Action failed: c:compName$controller$methodName [WeakMap.prototype.set: 'key' is not an object]`.

`window.location` seems to work fine in the JavaScript console and on other pages in Edge, so we're pretty sure this is not a bug in Edge.

**Comment by mgetzbw** [comment]
The supported methods on [Window are documented](http://documentation.auraframework.org/lockerApiTest/secureWindow.app?aura.mode=DEV)

**Comment by ravijayaramappa** [comment]
Filed a bug on on Locker Service team to investigate this : W-4146185

**Comment by ravijayaramappa** [comment]
This is actually caused by a bug in Microsoft Edge. It has been previously reported and I have filed an issue for the MS team(https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12112572/)

SE post for the same issue:
https://salesforce.stackexchange.com/questions/176873/ms-edge-error-when-accessing-window-location-in-lightning-components-with-lock

**Comment by ravijayaramappa** [comment]
@chirag64 Please review my comment above and close this issue if you are satisfied with the answer.

**Comment by chirag64** [comment]
Thanks Ravi, I guess there's not much we can do here except wait for Microsoft to patch this in Edge. 👍🏼
