### ISSUE TITLE
Problem with SecureElement.isValidAttributeName

### ISSUE THREAD

**Issue by marcantoineveilleux** [forcedotcom/aura#141]
There is a problem here: https://github.com/forcedotcom/aura/blob/master/aura-resources/src/main/resources/aura/resources/lockerservice/aura-locker.js#L1821

When `name` is `undefined`, you'll get an error when trying to call `indexOf`.

You can easily reproduce the problem with `element.getAttribute(undefined)`. When locker service is enabled, it throws an error. When it is disabled, a standard element will simply return `null`.

**Comment by erocheleau** [comment]
I am running into the same issue.

By the specification of w3: https://www.w3.org/TR/DOM-Level-2-Core/core.html#ID-666EE0F9

This should not throw. And if you test this method on a normal HTML DOM element, `randomElement.getAttribute(undefined|null|missingAttribute)` it returns `null`. Does not throw an error.

The problem is that you do not check if `name` exists before trying to call `name.indexOf("-")` here: https://github.com/forcedotcom/aura/blob/master/aura-resources/src/main/resources/aura/resources/lockerservice/aura-locker.js#L3929

**Comment by jfparadis** [comment]
Filed W-4740289
