### ISSUE TITLE
ui:select does not have a default value

### ISSUE THREAD

**Issue by nkint** [forcedotcom/aura#36]
Hi!
I'm posting after this question:
http://salesforce.stackexchange.com/questions/73733/how-retrive-the-value-from-uiinputselect/

if I write
`component.find('o').get('v.value');`

before selecting an option I get `undefined` while in the rendered element I see the first option.
please add a default value to be consistent with the rendered element.

**Comment by dianawidjaja** [comment]
Are you retrieving the value in an init handler? Since the element won't be available in the DOM at that time, you might have to use a different attribute like this:
`<aura:attribute name="selectedContact" type="String" default="{!v.contacts[0].Id}"/>`
You can then retrieve the value in your init handler.
`var selected = component.get("v.selectedContact");`
Please let me know if that works for you and I can update the answer on stackexchange.

**Comment by nkint** [comment]
no it is not in init handler. it is in a press handler of a confirm button..

**Comment by dianawidjaja** [comment]
We filed a bug for this. It looks like we need to pull the options out of aura:iteration before retrieving the initial value. Thanks for catching this!
