### ISSUE TITLE
ArrayIndexOutOfBoundsException at Jetty startup of unmodified sample app

### ISSUE THREAD

**Issue by pozil** [forcedotcom/aura#72]
Issue affecting Aura v0.5017.

I am following the startup guide from the readme and was able to build the sample app (note that I did not modify it in any way).

When starting Jetty, there are 2 ArrayIndexOutOfBoundsException that occur (see attached [full logs](https://github.com/forcedotcom/aura/files/621506/aura-sample-build-n-run.txt)).

These errors are related to the loading of Aura classes in JARs (`org/auraframework/def/genericxml/GenericXmlValidator.class` and `org/auraframework/impl/DefinitionServiceImpl.class`) by `org.objectweb.asm.ClassReader`.

At first I suspected that Maven downloaded corrupt binaries so I purged the whole repository but after retrying the problem is not fixed. Could it be on your end?

I am unsure of the impact of these errors as these do not seem to be blocking: I am able to view the sample app.

**Comment by pozil** [comment]
This seems to be coming from Jetty:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=414507

Issue is fixed in jetty-7.6.13, 8.1.13, 9.0.5 and 9.1.
But the Aura project is running 8.1.11.

Upgrading to Jetty to later 8.1.x versions did not fix the issue.

**Comment by pozil** [comment]
By the way, I just noticed that the sample app archetype does not use the latest Aura version.
I updated the project to Aura v0.5020 but the issue remains.

**Comment by pozil** [comment]
Updating to the latest Jetty server (9.3.14.v20161028) fixed the issue.

Please apply those changes in the archetype:
- use latest version of Aura
- use newer version of Jetty (current one dates from May 2013)

**Comment by wolfch** [comment]
I have more information regarding this bug.

Upon startup of Jetty, there are numerous exceptions thrown as various classes are scanned for bytecode manipulation by Jetty via asm:
```
java.lang.ArrayIndexOutOfBoundsException: 29146
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:898)
	[...]
```
This appears to be due to using Jetty 8.x which includes a version of asm that can't handle Java8 bytecode:

http://stackoverflow.com/questions/26496338/strange-java-lang-arrayindexoutofboundsexception-thrown-on-jetty-startup

The solution is to use asm-5.x or higher:	
http://forge.ow2.org/forum/forum.php?forum_id=2302

To get the correct version of asm, the correct version of Jetty should be used and that
should be at least 9.3.x, as @pozil has pointed out.  This version is also in Maven artifact group `org.eclipse.jetty`, no longer in `org.mortbay.jetty`.

See:  https://en.wikipedia.org/wiki/Jetty_(web_server)#History
